2025-03-26 11:36:28,840 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-26 11:36:32,579 [INFO] AcceptBooking - 预约成功：ww (tt@11.com)
2025-03-26 11:36:32,584 [INFO] basehttp - "POST /tourists/book/ HTTP/1.1" 200 18
2025-03-26 11:36:34,884 [INFO] basehttp - "GET /tourists/book/ HTTP/1.1" 200 1273
2025-03-26 11:36:41,270 [INFO] AcceptBooking - 预约成功：ww (tt@11.com)
2025-03-26 11:36:41,271 [INFO] basehttp - "POST /tourists/book/ HTTP/1.1" 200 18
2025-03-26 17:34:34,877 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\models.py changed, reloading.
2025-03-26 17:34:39,465 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-26 17:55:37,874 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py changed, reloading.
2025-03-26 17:55:40,242 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-26 17:59:15,373 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-26 17:59:18,022 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-26 18:01:28,080 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-26 18:01:30,539 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-26 18:02:44,408 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-26 18:02:46,922 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-26 18:10:04,173 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-26 18:12:44,344 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py changed, reloading.
2025-03-26 18:12:46,757 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-26 18:16:38,779 [WARNING] log - Not Found: /send_code
2025-03-26 18:16:38,781 [WARNING] basehttp - "GET /send_code HTTP/1.1" 404 2734
2025-03-26 18:17:18,643 [WARNING] log - Not Found: /tourists/send_code
2025-03-26 18:17:18,644 [WARNING] basehttp - "GET /tourists/send_code HTTP/1.1" 404 3440
2025-03-26 18:17:41,673 [WARNING] log - Not Found: /tourists/ send_code/
2025-03-26 18:17:41,674 [WARNING] basehttp - "GET /tourists/%20send_code/ HTTP/1.1" 404 3449
2025-03-26 18:17:52,709 [INFO] verification_service - 验证码已发送至邮箱：None
2025-03-26 18:17:52,712 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 52
2025-03-26 19:06:31,823 [INFO] verification_service - 验证码已发送至邮箱：None
2025-03-26 19:06:31,825 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 52
2025-03-26 19:08:56,988 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-26 19:09:00,390 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-26 19:19:17,296 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-26 19:19:21,257 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-26 19:20:04,395 [ERROR] verification_service - 验证码发送失败：name 'ValidationError' is not defined
2025-03-26 19:20:04,399 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 62
2025-03-26 19:20:55,807 [ERROR] verification_service - 验证码发送失败：name 'ValidationError' is not defined
2025-03-26 19:20:55,808 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 62
2025-03-26 20:27:56,455 [ERROR] verification_service - 验证码发送失败：name 'ValidationError' is not defined
2025-03-26 20:27:56,456 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 62
2025-03-26 20:28:10,287 [ERROR] verification_service - 验证码发送失败：name 'ValidationError' is not defined
2025-03-26 20:28:10,288 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 62
2025-03-26 20:28:58,532 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-26 20:29:02,061 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-26 20:29:10,372 [ERROR] verification_service - 验证码发送失败：name 'JsonResponse' is not defined
2025-03-26 20:29:10,374 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 62
2025-03-26 20:30:27,587 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-26 20:30:30,446 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-26 20:30:36,701 [ERROR] log - Internal Server Error: /tourists/send_code/
Traceback (most recent call last):
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py", line 43, in send_verification_code
    return JsonResponse(result)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\http\response.py", line 726, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2025-03-26 20:30:36,708 [ERROR] basehttp - "GET /tourists/send_code/ HTTP/1.1" 500 73205
2025-03-26 20:31:20,074 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-26 20:31:23,315 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-26 20:31:52,686 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-26 20:31:56,656 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-26 20:32:22,005 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-26 20:32:25,184 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-26 20:32:33,640 [INFO] verification_service - 验证码已发送至邮箱：None
2025-03-26 20:32:33,643 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 52
2025-03-27 11:35:24,385 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verify.py changed, reloading.
2025-03-27 11:35:27,250 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 11:36:44,804 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Backend\celery.py changed, reloading.
2025-03-27 11:36:47,334 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 11:37:34,676 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\__init__.py changed, reloading.
2025-03-27 11:37:37,197 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 11:43:31,985 [ERROR] __init__ - VerificationService: 加载任务失败 - No module named 'Tourists_in_HKU.verify'
2025-03-27 11:43:31,986 [ERROR] __init__ - VerificationService: 加载验证码服务失败 - No module named 'Tourists_in_HKU.verification_service'
2025-03-27 11:43:36,054 [ERROR] __init__ - VerificationService: 加载任务失败 - No module named 'Tourists_in_HKU.verify'
2025-03-27 11:43:36,056 [ERROR] __init__ - VerificationService: 加载验证码服务失败 - No module named 'Tourists_in_HKU.verification_service'
2025-03-27 11:43:36,206 [ERROR] __init__ - VerificationService: 加载任务失败 - No module named 'Tourists_in_HKU.verify'
2025-03-27 11:43:36,207 [ERROR] __init__ - VerificationService: 加载验证码服务失败 - No module named 'Tourists_in_HKU.verification_service'
2025-03-27 11:43:36,361 [ERROR] __init__ - VerificationService: 加载任务失败 - No module named 'Tourists_in_HKU.verify'
2025-03-27 11:43:36,362 [ERROR] __init__ - VerificationService: 加载验证码服务失败 - No module named 'Tourists_in_HKU.verification_service'
2025-03-27 11:43:36,567 [ERROR] __init__ - VerificationService: 加载任务失败 - No module named 'Tourists_in_HKU.verify'
2025-03-27 11:43:36,568 [ERROR] __init__ - VerificationService: 加载验证码服务失败 - No module named 'Tourists_in_HKU.verification_service'
2025-03-27 11:43:36,635 [ERROR] __init__ - VerificationService: 加载任务失败 - No module named 'Tourists_in_HKU.verify'
2025-03-27 11:43:36,637 [ERROR] __init__ - VerificationService: 加载验证码服务失败 - No module named 'Tourists_in_HKU.verification_service'
2025-03-27 11:43:36,857 [ERROR] __init__ - VerificationService: 加载任务失败 - No module named 'Tourists_in_HKU.verify'
2025-03-27 11:43:36,858 [ERROR] __init__ - VerificationService: 加载验证码服务失败 - No module named 'Tourists_in_HKU.verification_service'
2025-03-27 11:43:36,985 [ERROR] __init__ - VerificationService: 加载任务失败 - No module named 'Tourists_in_HKU.verify'
2025-03-27 11:43:36,986 [ERROR] __init__ - VerificationService: 加载验证码服务失败 - No module named 'Tourists_in_HKU.verification_service'
2025-03-27 11:43:37,377 [ERROR] __init__ - VerificationService: 加载任务失败 - No module named 'Tourists_in_HKU.verify'
2025-03-27 11:43:37,378 [ERROR] __init__ - VerificationService: 加载验证码服务失败 - No module named 'Tourists_in_HKU.verification_service'
2025-03-27 11:45:26,657 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 11:45:26,657 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 11:45:30,747 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 11:45:30,748 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 11:45:30,922 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 11:45:30,923 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 11:45:31,143 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 11:45:31,143 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 11:45:31,240 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 11:45:31,241 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 11:45:31,446 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 11:45:31,448 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 11:45:31,727 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 11:45:31,728 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 11:45:31,946 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 11:45:31,947 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 11:45:32,077 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 11:45:32,078 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 11:46:47,999 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 11:46:47,999 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 11:46:50,173 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 11:46:50,175 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 11:46:50,339 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 11:46:59,988 [INFO] verification_service - 验证码已发送至邮箱：None
2025-03-27 11:46:59,989 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 52
2025-03-27 12:30:26,779 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-27 12:30:30,658 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 12:30:30,658 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 12:30:30,901 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 12:31:00,631 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 12:31:00,632 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 12:31:04,949 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 12:31:04,949 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 12:31:05,221 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 12:31:05,221 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 12:31:05,270 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 12:31:05,271 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 12:31:05,450 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 12:31:05,451 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 12:31:05,527 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 12:31:05,527 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 12:31:05,871 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 12:31:05,871 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 12:31:05,942 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 12:31:05,943 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 12:31:06,261 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 12:31:06,262 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 12:31:13,572 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 12:31:13,572 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 12:31:15,982 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 12:31:15,983 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 12:31:16,166 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 12:32:53,445 [INFO] verification_service - 验证码已发送至邮箱：None
2025-03-27 12:32:53,447 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 12:33:40,233 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-27 12:33:42,524 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 12:33:42,524 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 12:33:42,695 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 12:33:48,644 [INFO] verification_service - 验证码已发送至邮箱：None
2025-03-27 12:33:48,646 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 12:42:48,683 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Backend\settings.py changed, reloading.
2025-03-27 12:42:51,000 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 12:42:51,001 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 12:42:51,191 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 12:43:15,516 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 12:43:15,517 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 12:43:17,639 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 12:43:17,640 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 12:43:17,814 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 12:43:22,520 [INFO] verification_service - 验证码已发送至邮箱：None
2025-03-27 12:43:22,521 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 12:58:02,040 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-27 12:58:04,560 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 12:58:04,560 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 12:58:04,739 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 12:58:14,056 [INFO] verification_service - 验证码已发送至邮箱：None
2025-03-27 12:58:14,057 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 12:58:54,995 [INFO] verification_service - 验证码已发送至邮箱：None
2025-03-27 12:58:54,996 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 13:00:07,669 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Backend\settings.py changed, reloading.
2025-03-27 13:00:10,104 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:00:10,104 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:00:10,258 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 13:00:56,354 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:00:56,355 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:00:58,418 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:00:58,419 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:00:58,592 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 13:01:26,679 [INFO] AcceptBooking - 预约成功：Zhang Junchi (5151515@163.com)
2025-03-27 13:01:26,680 [INFO] basehttp - "POST /tourists/book/ HTTP/1.1" 200 18
2025-03-27 13:01:52,631 [INFO] AcceptBooking - 预约成功：Zhang Junchi (2577933967@qq.com)
2025-03-27 13:01:52,632 [INFO] basehttp - "POST /tourists/book/ HTTP/1.1" 200 18
2025-03-27 13:07:03,613 [INFO] AcceptBooking - 预约成功：Zhang Junchi (2577933967@qq.com)
2025-03-27 13:07:03,615 [INFO] basehttp - "POST /tourists/book/ HTTP/1.1" 200 18
2025-03-27 13:07:50,026 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\SendEmail.py changed, reloading.
2025-03-27 13:07:52,457 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:07:52,457 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:07:52,642 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 13:11:44,727 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:11:44,728 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:12:42,434 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:12:42,435 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:12:44,918 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:12:44,918 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:12:45,077 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 13:12:54,644 [INFO] AcceptBooking - 预约成功：Zhang Junchi (2577933967@qq.com)
2025-03-27 13:12:54,646 [INFO] basehttp - "POST /tourists/book/ HTTP/1.1" 200 18
2025-03-27 13:13:23,909 [INFO] verification_service - 验证码已发送至邮箱：None
2025-03-27 13:13:23,911 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 13:14:28,369 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\SendEmail.py changed, reloading.
2025-03-27 13:14:31,121 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:14:31,121 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:14:31,310 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 13:15:43,884 [INFO] AcceptBooking - 预约成功：luowei (u3638153@connect.hku.hk)
2025-03-27 13:15:43,886 [INFO] basehttp - "POST /tourists/book/ HTTP/1.1" 200 18
2025-03-27 13:19:00,085 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:19:00,085 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:19:17,995 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:19:17,995 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:19:20,474 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:19:20,475 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:19:20,669 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 13:19:34,787 [INFO] verification_service - 验证码已发送至邮箱：None
2025-03-27 13:19:34,789 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 13:22:01,619 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-27 13:22:03,858 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:22:03,859 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:22:04,037 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 13:22:13,232 [ERROR] verification_service - 验证码发送失败：'function' object has no attribute 'delay'
2025-03-27 13:22:13,236 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 66
2025-03-27 13:23:10,646 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-27 13:23:13,330 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 13:23:56,189 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-27 13:23:58,592 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:23:58,593 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:23:58,841 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 13:24:04,977 [ERROR] verification_service - 验证码发送失败：'function' object has no attribute 'delay'
2025-03-27 13:24:04,978 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 66
2025-03-27 13:26:03,073 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verify.py changed, reloading.
2025-03-27 13:26:05,400 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:26:05,400 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:26:05,572 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 13:26:12,222 [INFO] verification_service - 验证码已发送至邮箱：None
2025-03-27 13:26:12,223 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 13:37:07,189 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verify.py changed, reloading.
2025-03-27 13:37:09,363 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:37:09,364 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:37:09,506 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 13:37:18,169 [INFO] verification_service - 验证码已发送至邮箱：None
2025-03-27 13:37:18,170 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 13:39:05,784 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verify.py changed, reloading.
2025-03-27 13:39:08,452 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:39:08,452 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:39:08,635 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 13:39:35,478 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Backend\celery.py changed, reloading.
2025-03-27 13:39:38,206 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:39:38,207 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:39:38,374 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 13:40:46,392 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:40:46,392 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:41:21,657 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:41:21,658 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:41:23,797 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:41:23,799 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:41:23,980 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 13:41:29,190 [INFO] verification_service - 验证码已发送至邮箱：None
2025-03-27 13:41:29,191 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 13:41:29,196 [INFO] verify - 验证码邮件已成功发送给 None
2025-03-27 13:42:38,109 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verify.py changed, reloading.
2025-03-27 13:42:40,272 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:42:40,272 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:42:40,420 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 13:42:50,830 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verify.py changed, reloading.
2025-03-27 13:42:53,077 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:42:53,077 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:42:53,244 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 13:42:58,560 [INFO] verification_service - 验证码已发送至邮箱：None
2025-03-27 13:42:58,561 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 13:42:58,562 [INFO] verify - 验证码邮件已成功发送给 None
2025-03-27 13:43:25,510 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verify.py changed, reloading.
2025-03-27 13:43:27,774 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:43:27,774 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:43:27,945 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 13:56:31,623 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py changed, reloading.
2025-03-27 13:56:33,878 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:56:33,878 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:56:34,074 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 13:56:50,922 [INFO] verification_service - 验证码已发送至邮箱：None
2025-03-27 13:56:50,923 [INFO] basehttp - "GET /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 13:56:50,924 [INFO] verify - 验证码邮件已成功发送给 None
2025-03-27 13:58:51,412 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py changed, reloading.
2025-03-27 13:58:53,801 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 13:58:53,801 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 13:58:53,978 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 14:07:23,480 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py changed, reloading.
2025-03-27 14:07:25,779 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 14:07:25,780 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 14:07:25,954 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 14:07:52,484 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py changed, reloading.
2025-03-27 14:07:54,863 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 14:07:54,863 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 14:07:55,023 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 14:08:06,119 [ERROR] log - Internal Server Error: /tourists/send_code/
Traceback (most recent call last):
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py", line 42, in send_verification_code
    form = BookingForm(request.GET)
NameError: name 'BookingForm' is not defined
2025-03-27 14:08:06,123 [ERROR] basehttp - "GET /tourists/send_code/ HTTP/1.1" 500 67859
2025-03-27 14:11:01,941 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py changed, reloading.
2025-03-27 14:11:04,648 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 14:11:04,648 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 14:11:04,834 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 14:16:53,541 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py changed, reloading.
2025-03-27 14:16:56,180 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 14:16:56,180 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 14:16:56,345 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 14:17:08,391 [INFO] verification_service - 验证码已发送至邮箱：tiffanyluo2868@163.com
2025-03-27 14:17:08,393 [INFO] basehttp - "POST /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 14:17:11,573 [INFO] verify - 验证码邮件已成功发送给 tiffanyluo2868@163.com
2025-03-27 14:18:55,494 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verify.py changed, reloading.
2025-03-27 14:18:58,335 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 14:18:58,336 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 14:18:58,515 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 14:19:21,097 [INFO] verification_service - 验证码已发送至邮箱：tiffanyluo2868@163.com
2025-03-27 14:19:21,098 [INFO] basehttp - "POST /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 14:19:49,467 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verify.py changed, reloading.
2025-03-27 14:19:52,160 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 14:19:52,160 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 14:19:52,347 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 14:39:32,387 [INFO] verification_service - 验证码已发送至邮箱：tiffanyluo2868@163.com
2025-03-27 14:39:32,389 [INFO] basehttp - "POST /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 14:39:35,411 [INFO] verify - 验证码邮件已成功发送给 tiffanyluo2868@163.com
2025-03-27 14:39:48,117 [INFO] verification_service - 验证码已发送至邮箱：2577933967@qq.com
2025-03-27 14:39:48,118 [INFO] basehttp - "POST /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 14:39:51,188 [INFO] verify - 验证码邮件已成功发送给 2577933967@qq.com
2025-03-27 15:32:52,258 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verify.py changed, reloading.
2025-03-27 15:32:58,828 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 15:32:58,829 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 15:32:59,247 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 15:44:25,445 [INFO] verification_service - 验证码已发送至邮箱：2577933967@qq.com
2025-03-27 15:44:25,447 [INFO] basehttp - "POST /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 15:44:27,270 [INFO] verification_service - 验证码已发送至邮箱：2577933967@qq.com
2025-03-27 15:44:27,272 [INFO] basehttp - "POST /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 15:44:28,601 [INFO] verify - 验证码邮件已成功发送给 2577933967@qq.com
2025-03-27 15:44:30,330 [INFO] verification_service - 验证码已发送至邮箱：2577933967@qq.com
2025-03-27 15:44:30,332 [INFO] basehttp - "POST /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 15:44:32,127 [INFO] verification_service - 验证码已发送至邮箱：2577933967@qq.com
2025-03-27 15:44:32,129 [INFO] basehttp - "POST /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 15:44:32,344 [INFO] verify - 验证码邮件已成功发送给 2577933967@qq.com
2025-03-27 15:44:35,794 [INFO] verify - 验证码邮件已成功发送给 2577933967@qq.com
2025-03-27 15:44:39,438 [INFO] verify - 验证码邮件已成功发送给 2577933967@qq.com
2025-03-27 15:44:46,374 [INFO] verification_service - 验证码已发送至邮箱：u3638153@connect.hku.hk
2025-03-27 15:44:46,375 [INFO] basehttp - "POST /tourists/send_code/ HTTP/1.1" 200 58
2025-03-27 15:44:49,113 [INFO] verify - 验证码邮件已成功发送给 u3638153@connect.hku.hk
2025-03-27 15:48:54,178 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-27 15:48:57,428 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 15:48:57,429 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 15:48:57,705 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 15:49:21,480 [INFO] verification_service - 邮箱 2577933967@qq.com 的验证码已存在，未重新生成
2025-03-27 15:49:21,482 [INFO] basehttp - "POST /tourists/send_code/ HTTP/1.1" 200 66
2025-03-27 15:49:24,885 [INFO] verification_service - 邮箱 2577933967@qq.com 的验证码已存在，未重新生成
2025-03-27 15:49:24,886 [INFO] basehttp - "POST /tourists/send_code/ HTTP/1.1" 200 66
2025-03-27 15:49:26,694 [INFO] verification_service - 邮箱 2577933967@qq.com 的验证码已存在，未重新生成
2025-03-27 15:49:26,696 [INFO] basehttp - "POST /tourists/send_code/ HTTP/1.1" 200 66
2025-03-27 15:50:14,299 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-27 15:50:18,625 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 15:50:18,626 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 15:50:18,905 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 20:48:44,945 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py changed, reloading.
2025-03-27 20:48:53,439 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 20:48:53,439 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 20:48:53,891 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 21:34:26,215 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py changed, reloading.
2025-03-27 21:34:29,843 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 21:34:29,843 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 21:34:30,178 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 21:35:46,818 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py changed, reloading.
2025-03-27 21:35:49,428 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 21:35:49,429 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 21:35:49,623 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 21:38:23,121 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py changed, reloading.
2025-03-27 21:38:26,102 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 21:38:26,103 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 21:38:26,333 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 21:40:59,880 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py changed, reloading.
2025-03-27 21:41:02,543 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 21:41:02,544 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 21:41:02,735 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 21:46:21,460 [INFO] verification_service - 验证码已发送至邮箱：2577933967@qq.com
2025-03-27 21:46:21,464 [INFO] basehttp - "POST /tourists/send_code/ HTTP/1.1" 200 52
2025-03-27 21:46:25,089 [INFO] verify - 验证码邮件已成功发送给 2577933967@qq.com
2025-03-27 21:46:49,973 [ERROR] log - Internal Server Error: /tourists/verify_code/
2025-03-27 21:46:49,974 [ERROR] basehttp - "POST /tourists/verify_code/ HTTP/1.1" 500 75
2025-03-27 21:47:26,919 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\urls.py changed, reloading.
2025-03-27 21:47:29,472 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 21:47:29,472 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 21:47:29,690 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 21:48:21,524 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\urls.py changed, reloading.
2025-03-27 21:48:24,844 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 21:48:24,845 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 21:48:25,127 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 21:49:15,566 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\urls.py changed, reloading.
2025-03-27 21:49:18,208 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 21:49:18,209 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 21:49:18,408 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 21:50:16,404 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\urls.py changed, reloading.
2025-03-27 21:50:18,940 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 21:50:18,940 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 21:50:19,130 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 21:50:48,876 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\urls.py changed, reloading.
2025-03-27 21:50:51,253 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-27 21:50:51,253 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-27 21:50:51,450 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-27 21:51:04,782 [ERROR] log - Internal Server Error: /tourists/verify_code/
2025-03-27 21:51:04,783 [ERROR] basehttp - "POST /tourists/verify_code/ HTTP/1.1" 500 75
2025-03-27 21:51:10,011 [ERROR] log - Internal Server Error: /tourists/verify_code/
2025-03-27 21:51:10,013 [ERROR] basehttp - "POST /tourists/verify_code/ HTTP/1.1" 500 75
2025-03-28 10:57:19,004 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\urls.py changed, reloading.
2025-03-28 10:57:30,300 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-28 10:57:30,301 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-28 10:57:31,305 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-28 10:57:50,378 [INFO] verification_service - 验证码已发送至邮箱：2577933967@qq.com
2025-03-28 10:57:50,382 [INFO] basehttp - "POST /tourists/send_code/ HTTP/1.1" 200 52
2025-03-28 10:57:53,959 [INFO] verify - 验证码邮件已成功发送给 2577933967@qq.com
2025-03-28 10:58:44,783 [ERROR] log - Internal Server Error: /tourists/verify_code/
2025-03-28 10:58:44,786 [ERROR] basehttp - "POST /tourists/verify_code/ HTTP/1.1" 500 75
2025-03-28 11:00:49,020 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py changed, reloading.
2025-03-28 11:00:54,734 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-28 11:00:54,735 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-28 11:00:55,077 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-28 11:01:06,666 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py changed, reloading.
2025-03-28 11:01:20,617 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-28 11:01:20,619 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-28 11:01:21,213 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-28 11:02:02,176 [INFO] VerifyEmailCode - 从 Redis 中获取验证码：307770 对应邮箱：2577933967@qq.com
2025-03-28 11:02:02,178 [INFO] VerifyEmailCode - 验证码验证成功：2577933967@qq.com
2025-03-28 11:02:02,185 [INFO] basehttp - "POST /tourists/verify_code/ HTTP/1.1" 200 59
2025-03-28 11:06:25,256 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py changed, reloading.
2025-03-28 11:06:29,566 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-28 11:06:29,566 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-28 11:06:29,852 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-28 11:49:14,995 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\VerificationService\verification_service.py changed, reloading.
2025-03-28 11:49:20,418 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-03-28 11:49:20,419 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-03-28 11:49:20,728 [INFO] autoreload - Watching for file changes with StatReloader
2025-03-28 11:50:39,091 [INFO] VerifyEmailCode - Redis 中未找到验证码，邮箱：2577933967@qq.com
2025-03-28 11:50:39,092 [WARNING] VerifyEmailCode - 验证码不存在或已过期：2577933967@qq.com
2025-03-28 11:50:39,096 [INFO] basehttp - "POST /tourists/verify_code/ HTTP/1.1" 200 72
2025-04-05 23:37:35,953 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-05 23:37:35,955 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-05 23:37:38,281 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-05 23:37:38,281 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-05 23:37:38,453 [INFO] autoreload - Watching for file changes with StatReloader
2025-04-05 23:39:41,705 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\AcceptBooking.py changed, reloading.
2025-04-05 23:39:44,109 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-05 23:39:44,110 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-05 23:39:44,274 [INFO] autoreload - Watching for file changes with StatReloader
2025-04-05 23:40:44,398 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\models.py changed, reloading.
2025-04-05 23:40:47,001 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-05 23:40:47,001 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-05 23:40:47,259 [INFO] autoreload - Watching for file changes with StatReloader
2025-04-05 23:42:40,746 [ERROR] log - Internal Server Error: /tourists/book/
Traceback (most recent call last):
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tourists_in_hku.tourists_in_hku_booking' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py", line 20, in book_tour
    return book_tour_service(request)
  File "G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\AcceptBooking.py", line 19, in book_tour_service
    if Booking.objects.filter(email=email).exists():
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 660, in has_results
    return compiler.has_results()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'tourists_in_hku.tourists_in_hku_booking' doesn't exist")
2025-04-05 23:42:40,778 [ERROR] basehttp - "POST /tourists/book/ HTTP/1.1" 500 196049
2025-04-05 23:45:06,627 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-05 23:45:06,627 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-05 23:46:08,861 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-05 23:46:08,861 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-05 23:46:36,800 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-05 23:46:36,801 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-05 23:46:59,736 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-05 23:46:59,737 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-05 23:47:08,614 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-05 23:47:08,614 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-05 23:47:10,903 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-05 23:47:10,903 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-05 23:47:11,085 [INFO] autoreload - Watching for file changes with StatReloader
2025-04-05 23:47:27,506 [ERROR] log - Internal Server Error: /tourists/book/
Traceback (most recent call last):
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tourists_in_hku.tourists_in_hku_booking' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py", line 20, in book_tour
    return book_tour_service(request)
  File "G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\AcceptBooking.py", line 19, in book_tour_service
    if Booking.objects.filter(email=email).exists():
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 660, in has_results
    return compiler.has_results()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'tourists_in_hku.tourists_in_hku_booking' doesn't exist")
2025-04-05 23:47:27,523 [ERROR] basehttp - "POST /tourists/book/ HTTP/1.1" 500 196049
2025-04-05 23:48:31,121 [ERROR] log - Internal Server Error: /tourists/book/
Traceback (most recent call last):
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tourists_in_hku.tourists_in_hku_booking' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py", line 20, in book_tour
    return book_tour_service(request)
  File "G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\AcceptBooking.py", line 19, in book_tour_service
    if Booking.objects.filter(email=email).exists():
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 660, in has_results
    return compiler.has_results()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'tourists_in_hku.tourists_in_hku_booking' doesn't exist")
2025-04-05 23:48:31,137 [ERROR] basehttp - "POST /tourists/book/ HTTP/1.1" 500 196049
2025-04-05 23:49:05,006 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-05 23:49:05,006 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-05 23:49:07,158 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-05 23:49:07,159 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-05 23:49:07,329 [INFO] autoreload - Watching for file changes with StatReloader
2025-04-05 23:49:13,571 [ERROR] log - Internal Server Error: /tourists/book/
Traceback (most recent call last):
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tourists_in_hku.tourists_in_hku_booking' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py", line 20, in book_tour
    return book_tour_service(request)
  File "G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\AcceptBooking.py", line 19, in book_tour_service
    if Booking.objects.filter(email=email).exists():
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 660, in has_results
    return compiler.has_results()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'tourists_in_hku.tourists_in_hku_booking' doesn't exist")
2025-04-05 23:49:13,587 [ERROR] basehttp - "POST /tourists/book/ HTTP/1.1" 500 196049
2025-04-05 23:50:21,975 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-05 23:50:21,976 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-05 23:50:35,311 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-05 23:50:35,311 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-05 23:57:08,729 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-05 23:57:08,731 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-05 23:57:22,615 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-05 23:57:22,616 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-05 23:57:25,128 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-05 23:57:25,128 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-05 23:57:25,321 [INFO] autoreload - Watching for file changes with StatReloader
2025-04-05 23:57:42,497 [ERROR] AcceptBooking - 预约失败：(1364, "Field 'id' doesn't have a default value")
2025-04-05 23:57:42,500 [ERROR] log - Internal Server Error: /tourists/book/
2025-04-05 23:57:42,501 [ERROR] basehttp - "POST /tourists/book/ HTTP/1.1" 500 27
2025-04-06 00:01:39,832 [ERROR] AcceptBooking - 预约失败：send_success_email() takes 2 positional arguments but 3 were given
2025-04-06 00:01:39,833 [ERROR] log - Internal Server Error: /tourists/book/
2025-04-06 00:01:39,834 [ERROR] basehttp - "POST /tourists/book/ HTTP/1.1" 500 27
2025-04-06 00:04:55,358 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\SendEmail.py changed, reloading.
2025-04-06 00:04:57,644 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:04:57,645 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:04:57,806 [INFO] autoreload - Watching for file changes with StatReloader
2025-04-06 00:05:06,172 [INFO] AcceptBooking - 重复预约尝试：2577933967@qq.com
2025-04-06 00:05:06,174 [WARNING] log - Bad Request: /tourists/book/
2025-04-06 00:05:06,175 [WARNING] basehttp - "POST /tourists/book/ HTTP/1.1" 400 52
2025-04-06 00:05:31,329 [INFO] AcceptBooking - 重复预约尝试：2577933967@qq.com
2025-04-06 00:05:31,330 [WARNING] log - Bad Request: /tourists/book/
2025-04-06 00:05:31,331 [WARNING] basehttp - "POST /tourists/book/ HTTP/1.1" 400 52
2025-04-06 00:07:11,526 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\AcceptBooking.py changed, reloading.
2025-04-06 00:07:14,111 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:07:14,112 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:07:14,291 [INFO] autoreload - Watching for file changes with StatReloader
2025-04-06 00:07:28,059 [INFO] AcceptBooking - 重复预约尝试：2577933967@qq.com
2025-04-06 00:08:56,438 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\SendEmail.py changed, reloading.
2025-04-06 00:08:58,937 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:08:58,938 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:08:59,113 [INFO] autoreload - Watching for file changes with StatReloader
2025-04-06 00:09:31,390 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\AcceptBooking.py changed, reloading.
2025-04-06 00:09:33,807 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:09:33,808 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:09:33,976 [INFO] autoreload - Watching for file changes with StatReloader
2025-04-06 00:10:06,186 [INFO] AcceptBooking - 重复预约尝试：2577933967@qq.com
2025-04-06 00:11:38,755 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\AcceptBooking.py changed, reloading.
2025-04-06 00:11:41,513 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:11:41,513 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:11:41,682 [INFO] autoreload - Watching for file changes with StatReloader
2025-04-06 00:11:57,424 [INFO] AcceptBooking - 重复预约尝试：tiffanyluo2868@163.com
2025-04-06 00:11:57,425 [WARNING] log - Bad Request: /tourists/book/
2025-04-06 00:11:57,426 [WARNING] basehttp - "POST /tourists/book/ HTTP/1.1" 400 52
2025-04-06 00:15:43,339 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\AcceptBooking.py changed, reloading.
2025-04-06 00:15:45,896 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:15:45,897 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:15:46,066 [INFO] autoreload - Watching for file changes with StatReloader
2025-04-06 00:16:10,049 [WARNING] AcceptBooking - 表单验证失败
2025-04-06 00:16:10,050 [WARNING] log - Bad Request: /tourists/book/
2025-04-06 00:16:10,050 [WARNING] basehttp - "POST /tourists/book/ HTTP/1.1" 400 28
2025-04-06 00:17:10,326 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\AcceptBooking.py changed, reloading.
2025-04-06 00:17:13,066 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:17:13,067 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:17:13,244 [INFO] autoreload - Watching for file changes with StatReloader
2025-04-06 00:17:25,469 [INFO] AcceptBooking - 重复预约尝试：2577933967@qq.com
2025-04-06 00:17:25,470 [WARNING] log - Bad Request: /tourists/book/
2025-04-06 00:17:25,471 [WARNING] basehttp - "POST /tourists/book/ HTTP/1.1" 400 52
2025-04-06 00:19:22,802 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:19:22,803 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:19:25,805 [ERROR] AcceptBooking - 预约失败：Error 10061 connecting to localhost:6379. 由于目标计算机积极拒绝，无法连接。.
2025-04-06 00:19:25,807 [ERROR] log - Internal Server Error: /tourists/book/
2025-04-06 00:19:25,817 [ERROR] basehttp - "POST /tourists/book/ HTTP/1.1" 500 27
2025-04-06 00:19:27,935 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:19:27,938 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:19:28,250 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:19:28,251 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:19:28,756 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:19:28,758 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:19:28,849 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:19:28,851 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:19:29,204 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:19:29,205 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:19:29,421 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:19:29,421 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:19:29,719 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:19:29,720 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:19:29,859 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:19:29,860 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:25:28,071 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:25:28,071 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:25:32,546 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:25:32,547 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:25:32,678 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:25:32,680 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:25:32,851 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:25:32,853 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:25:33,094 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:25:33,094 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:25:33,230 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:25:33,231 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:25:33,280 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:25:33,283 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:25:33,670 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:25:33,670 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:25:33,901 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:25:33,903 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:25:50,763 [INFO] AcceptBooking - 重复预约尝试：257793396@qq.com
2025-04-06 00:25:50,763 [WARNING] log - Bad Request: /tourists/book/
2025-04-06 00:25:50,764 [WARNING] basehttp - "POST /tourists/book/ HTTP/1.1" 400 52
2025-04-06 00:26:00,052 [INFO] AcceptBooking - 预约成功：257793376@qq.com，2021-10-02，时段A
2025-04-06 00:26:00,053 [INFO] basehttp - "POST /tourists/book/ HTTP/1.1" 200 34
2025-04-06 00:26:50,889 [INFO] AcceptBooking - 预约成功：2577933967@qq.com，2021-10-02，时段A
2025-04-06 00:26:50,891 [INFO] basehttp - "POST /tourists/book/ HTTP/1.1" 200 34
2025-04-06 00:30:32,020 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\SendEmail.py changed, reloading.
2025-04-06 00:30:34,766 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 00:30:34,767 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 00:30:34,945 [INFO] autoreload - Watching for file changes with StatReloader
2025-04-06 00:30:40,748 [ERROR] AcceptBooking - 预约失败：'function' object has no attribute 'delay'
2025-04-06 00:30:40,750 [ERROR] log - Internal Server Error: /tourists/book/
2025-04-06 00:30:40,754 [ERROR] basehttp - "POST /tourists/book/ HTTP/1.1" 500 27
2025-04-06 10:38:30,320 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\AcceptBooking.py changed, reloading.
2025-04-06 10:38:33,240 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 10:38:33,240 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 10:38:33,437 [INFO] autoreload - Watching for file changes with StatReloader
2025-04-06 10:39:31,281 [ERROR] AcceptBooking - 预约失败：name 'logger' is not defined
2025-04-06 10:39:31,282 [ERROR] log - Internal Server Error: /tourists/book/
2025-04-06 10:39:31,283 [ERROR] basehttp - "POST /tourists/book/ HTTP/1.1" 500 27
2025-04-06 10:39:57,234 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\AcceptBooking.py changed, reloading.
2025-04-06 10:39:59,551 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 10:39:59,551 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 10:39:59,723 [INFO] autoreload - Watching for file changes with StatReloader
2025-04-06 10:40:08,404 [ERROR] log - Internal Server Error: /tourists/book/
Traceback (most recent call last):
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\25779\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\views.py", line 20, in book_tour
    return book_tour_service(request)
  File "G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\AcceptBooking.py", line 21, in book_tour_service
    logger.info(f'重复预约尝试：{email}')
NameError: name 'logger' is not defined
2025-04-06 10:40:08,410 [ERROR] basehttp - "POST /tourists/book/ HTTP/1.1" 500 72696
2025-04-06 10:41:21,986 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\AcceptBooking.py changed, reloading.
2025-04-06 10:41:24,909 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 10:41:24,909 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 10:41:25,125 [INFO] autoreload - Watching for file changes with StatReloader
2025-04-06 10:41:32,667 [INFO] AcceptBooking - 重复预约尝试：257793367@qq.com
2025-04-06 10:41:32,669 [WARNING] log - Bad Request: /tourists/book/
2025-04-06 10:41:32,670 [WARNING] basehttp - "POST /tourists/book/ HTTP/1.1" 400 52
2025-04-06 10:41:49,646 [ERROR] AcceptBooking - 预约失败：name 'logger' is not defined
2025-04-06 10:41:49,648 [ERROR] log - Internal Server Error: /tourists/book/
2025-04-06 10:41:49,649 [ERROR] basehttp - "POST /tourists/book/ HTTP/1.1" 500 27
2025-04-06 10:43:28,688 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\SendEmail.py changed, reloading.
2025-04-06 10:43:31,023 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 10:43:31,023 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 10:43:31,192 [INFO] autoreload - Watching for file changes with StatReloader
2025-04-06 10:43:38,916 [INFO] AcceptBooking - 重复预约尝试：25779336@qq.com
2025-04-06 10:43:38,917 [WARNING] log - Bad Request: /tourists/book/
2025-04-06 10:43:38,918 [WARNING] basehttp - "POST /tourists/book/ HTTP/1.1" 400 52
2025-04-06 10:43:55,125 [INFO] SendEmail - 邮件已成功发送给 Dear Visitor (2577936@qq.com)
2025-04-06 10:43:55,127 [INFO] AcceptBooking - 预约成功：2577936@qq.com，2021-10-02，时段A
2025-04-06 10:43:55,130 [INFO] basehttp - "POST /tourists/book/ HTTP/1.1" 200 34
2025-04-06 10:45:14,678 [INFO] SendEmail - 邮件已成功发送给 Dear Visitor (tiffanyluo2868@163.com)
2025-04-06 10:45:14,679 [INFO] AcceptBooking - 预约成功：tiffanyluo2868@163.com，2021-10-02，时段A
2025-04-06 10:45:14,680 [INFO] basehttp - "POST /tourists/book/ HTTP/1.1" 200 34
2025-04-06 10:45:59,236 [INFO] autoreload - G:\MasterMaterial\SmartPhone\Project\Backend\Tourists_in_HKU\BookingService\SendEmail.py changed, reloading.
2025-04-06 10:46:01,489 [INFO] __init__ - VerificationService: 成功加载邮件发送任务
2025-04-06 10:46:01,490 [INFO] __init__ - VerificationService: 成功加载验证码服务
2025-04-06 10:46:01,659 [INFO] autoreload - Watching for file changes with StatReloader
